### ISSUE TITLE
Model read-in directory

### ISSUE THREAD

**Issue by jcjiang-dev** [fjebaker/lineprofiles#5]
The current model needs to read in files from the installation directory. PWD has to remain in the installation directory when in Xspec. If the model can allow users to change PWD, it would be nice, e.g., by offering the codes the absolute path of the model files (?).

**Comment by fjebaker** [comment]
Thanks @jcjiang-dev! 

For posterity, in the interim this was implemented in https://github.com/fjebaker/lineprofiles/commit/873f37c8ced52354ed297188d6ce4a77c097558b and I will make a release soon with the changes.

The model data directory can then be set with the environment variable `KLINE_PROF_DATA_DIR=/path/to/dir`.
